### ISSUE TITLE
Missing fluentd_config in map.jinja

### ISSUE THREAD

**Issue by mchugh19** [mitodl/fluentd-formula#7]
Applying the fluend.conf state returns an error:
```
# salt minionid state.sls fluentd.conf
minionid:
    Data failed to compile:
----------
    Rendering SLS 'base:fluentd.conf' failed: Jinja variable the template 'fluentd/map.jinja' (imported on line 1) does not export the requested name 'fluentd_config'
```

**Comment by blarghmatey** [comment]
@mchugh19 thanks for the report. The `.conf` state file is actually a leftover from the cookiecutter that was used to generate the formula. You actually want to use `.config` as that is what will properly generate the configuration data. That will render the pillar data into the FluentD configuration syntax for you.

If you run into issues with that we're happy to help.
